version: "3.8"

services:
  note-guard-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-guard-app
    depends_on:
      - note-guard-db
    ports:
      - "8000:8000"
    networks:
      - app-network

  note-guard-db:
    image: postgres:13
    container_name: note-guard-db
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - app-network

  note-guard-pgadmin:
    image: dpage/pgadmin4
    container_name: note-guard-pgadmin
    logging:
      driver: none 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    ports:
      - "80:80"
    depends_on:
      - note-guard-db
    networks:
      - app-network

networks:
  app-network:


